<svg xmlns="http://www.w3.org/2000/svg" width="128" height="128">
  <circle cx="64" cy="64" r="50" fill="yellow"/>
  <circle cx="44" cy="48" r="10" fill="black"/>
  <circle cx="84" cy="48" r="10" fill="black"/>
  <path d="M 32 80 Q 64 100 96 80" stroke="black" stroke-width="8" fill="none"/>
</svg>
